### ISSUE TITLE
Add the "build date" to the footer

### ISSUE THREAD

**Issue by TheRadialActive** [DerUser/hugo-material-docs#1]
If you have a repo, that has the whole website in it and where people are contributing to, it may nice to see, when the changes someone added, have been added with a look to the build date.

PS: We also can set a little bit more space between the main content and the footer.

**Comment by DerMolly** [comment]
apparently `{{ .Now }}` can be used for this purpose.

There should be an variable to activate this. Maybe `AddBuildTime`?

**Comment by DerMolly** [comment]
{{ .Now }} should not be used since hugo 0.20. Using [now](https://gohugo.io/functions/now/) instead

**Comment by DerMolly** [comment]
Could you provide an example string?

**Comment by TheRadialActive** [comment]
> Build with hugo: 29th Sep 2018, 09:34 pm

**Comment by DerMolly** [comment]
Like this?
![image](https://user-images.githubusercontent.com/3978662/46561993-649a1980-c8fa-11e8-9bd9-b70096af20d8.png)

**Comment by TheRadialActive** [comment]
Perfect! Thanks for your work!
