### ISSUE TITLE
"Download" should link to "Github releases" or custom url

### ISSUE THREAD

**Issue by TheRadialActive** [DerUser/hugo-material-docs#2]
Right now, the "Download" button on the left links to the zip of the master branch. Some software is more advanced, so they may want to point to the "Github releases". If they don't use github, they could link to something different, like a "Download" page.

**Comment by DerMolly** [comment]
I guess when you're using github master.zip is a good assumption.
However we could add
```
provider = "General"
repo_url = "https://github.com/sdaps/sdaps/releases"
```
instead of 
```
provider = "GitHub"
repo_url = "https://github.com/sdaps/sdaps"
```

in the config

**Comment by DerMolly** [comment]
Do we still want the Github Star Count?

**Comment by DerMolly** [comment]
The way to go seems to be changing this 

```
provider = "GitHub"
repo_url = "https://github.com/sdaps/sdaps"
```
to
```
use_github_stars = "true"
use_github_download = "true"
repo_url = "https://github.com/sdaps/sdaps"
custom_download_link = "https://github.com/sdaps/sdaps/releases"
```
