### ISSUE TITLE
fix modules

### ISSUE THREAD

**Issue by DerMolly** [DerUser/hugo-material-docs#3]
for now we can't auto-include modules when we use them as intended by the original author.

It may not be possible with the current state of hugo anymore

**Comment by mrdrogdrog** [comment]
The theme is using `{{ .Content }}` directly in layout.html.
Maybe(!) this issue could be solved if you put all the surrounding stuff of the content-command into baseof.html and define a main-block in single.html. (and use it in baseof.html)

**Comment by mrdrogdrog** [comment]
The new render sequence ( `baseof.html` encapsulates layout encapsulates content ) could solve this...

**Comment by mrdrogdrog** [comment]
https://gohugo.io/templates/base/#define-the-base-template
